DROP DATABASE IF EXISTS VUELOS;

CREATE DATABASE VUELOS;

USE VUELOS;


CREATE TABLE COMPANIAS (
id_compania VARCHAR(2),
nombre VARCHAR(20) NOT NULL,
nacionalidad VARCHAR(20) NOT NULL,
PRIMARY KEY (id_compania)
);


LOAD DATA INFILE 'F:\\Descargas\\7 - Vuelos\\Datos_Companias.txt' INTO TABLE COMPANIAS;

CREATE TABLE CLIENTES (
nif VARCHAR(9),
apellido1 VARCHAR(20) NOT NULL,
apellido2 VARCHAR(20) NOT NULL,
nombre VARCHAR(20) NOT NULL,
poblacion VARCHAR(20) NOT NULL,
PRIMARY KEY (nif)
);


LOAD DATA INFILE 'F:\\Descargas\\7 - Vuelos\\Datos_Clientes.txt' INTO TABLE CLIENTES;



CREATE TABLE VUELOS (
vuelo INT(4),
id_compania VARCHAR(2) NOT NULL,
fecha DATE NOT NULL,
origen VARCHAR(20) NOT NULL,
destino VARCHAR(20) NOT NULL,
plazas int(5) NOT NULL,
PRIMARY KEY (vuelo),
UNIQUE(origen,destino,fecha),
UNIQUE(vuelo,id_compania,fecha),
FOREIGN KEY(id_compania) REFERENCES COMPANIAS(id_compania)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);



LOAD DATA INFILE 'F:\\Descargas\\7 - Vuelos\\Datos_Vuelos.txt' INTO TABLE VUELOS;


CREATE TABLE OCUPACION_VUELOS (
vuelo int(4),
pasajero VARCHAR(9),
asiento VARCHAR(3),
observaciones VARCHAR(40),
PRIMARY KEY (vuelo,pasajero),
UNIQUE (vuelo,asiento),
FOREIGN KEY(vuelo) REFERENCES VUELOS(vuelo)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
FOREIGN KEY(pasajero) REFERENCES CLIENTES(nif)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);


CREATE TABLE RESERVAS (
vuelo int(4),
pasajero VARCHAR(9),
fecha_reserva DATE,
PRIMARY KEY (vuelo,pasajero,fecha_reserva),
FOREIGN KEY(vuelo) REFERENCES VUELOS(vuelo)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
FOREIGN KEY(pasajero) REFERENCES CLIENTES(nif)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);



CREATE TRIGGER RESERVA
AFTER INSERT ON OCUPACION_VUELOS
FOR EACH ROW 
INSERT INTO RESERVAS(vuelo,pasajero,fecha_reserva) VALUES(NEW.vuelo,NEW.pasajero,NOW());


INSERT INTO OCUPACION_VUELOS VALUES
(1005,'70589658A','1A',NULL),
(1005,'52587412D','3G',NULL),
(1005,'47852358S','4F','Bebe < 1 año'),
(7458,'74125896Q','2G','Silla de ruedas'),
(7458,'12547854F','3F',NULL),
(4712,'52587412D','1A',NULL),
(4712,'12547854F','5H',NULL),
(7525,'70589658A','2F',NULL);

INSERT INTO OCUPACION_VUELOS VALUES (4712,'47852358S','2A',NULL);

UPDATE OCUPACION_VUELOS
SET asiento='2C'
WHERE pasajero='47852358S' AND vuelo=4712;

SELECT * from OCUPACION_VUELOS;

SELECT * from RESERVAS;

INSERT INTO OCUPACION_VUELOS(vuelo,pasajero)
SELECT V.vuelo,'12547854F'
FROM VUELOS V
WHERE V.origen='BERLIN' AND V.destino='DUBLIN';

UPDATE OCUPACION_VUELOS
SET asiento='4B'
WHERE pasajero='12547854F' AND vuelo IN(
SELECT vuelo 
from VUELOS
WHERE origen='BERLIN' AND destino='DUBLIN');


SELECT * 
from CLIENTES
WHERE NIF IN (
SELECT pasajero
from OCUPACION_VUELOS
WHERE vuelo IN (
SELECT vuelo 
from VUELOS
WHERE origen='MADRID' AND destino='LONDRES' AND fecha='2024-04-23'));


SELECT *
from VUELOS
WHERE (MONTH(fecha)=5 OR MONTH(fecha)=6) AND YEAR(fecha)=2024; 

CREATE TRIGGER eliminar_reserva
BEFORE DELETE ON OCUPACION_VUELOS
FOR EACH ROW
DELETE FROM RESERVAS
WHERE vuelo=old.vuelo AND pasajero=old.pasajero;


DELETE FROM VUELOS WHERE origen='SEVILLA' AND destino='BARCELONA';

SELECT * from reservas;
SELECT * from OCUPACION_VUELOS;