DROP DATABASE IF EXISTS COMISARIA;

CREATE DATABASE COMISARIA;

USE COMISARIA;

CREATE TABLE ARMA(
	cod_arm VARCHAR(10) PRIMARY KEY,
	clase VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	policia VARCHAR(10) NOT NULL
	);
	
CREATE TABLE POLICIA(
	dni_pol VARCHAR(10) PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	categoria VARCHAR(50) NOT NULL,
	funcion VARCHAR(50) NOT NULL
	);
	
CREATE TABLE CALABOZO(
	cod_cal VARCHAR(10) PRIMARY KEY,
	ubicacion VARCHAR(50) NOT NULL
	);
	
CREATE TABLE CASO(
	cod_caso VARCHAR(10) PRIMARY KEY,
	juzgado VARCHAR(50) NOT NULL
	);