DELIMITER $$

DROP PROCEDURE IF EXISTS mayusculas $$

CREATE PROCEDURE mayusculas(cad1 VARCHAR(50), cad2 VARCHAR(50))
BEGIN
	SELECT CONCAT(UPPER(cad1),UPPER(cad2)) AS "MAYUSCULAS";
END $$

DELIMITER ;
