DELIMITER $$

DROP PROCEDURE IF EXISTS mes $$

CREATE PROCEDURE mes(IN m INT)
BEGIN
	CASE m
	WHEN 1 THEN SELECT "ENERO" AS "MES";
	WHEN 2 THEN SELECT "FEBRERO" AS "MES";
	WHEN 3 THEN SELECT "MARZO" AS "MES";
	WHEN 4 THEN SELECT "ABRIL" AS "MES";
	WHEN 5 THEN SELECT "MAYO" AS "MES";
	WHEN 6 THEN SELECT "JUNIO" AS "MES";
	WHEN 7 THEN SELECT "JULIO" AS "MES";
	WHEN 8 THEN SELECT "AGOSTO" AS "MES";
	WHEN 9 THEN SELECT "SEPTIEMBRE" AS "MES";
	WHEN 10 THEN SELECT "OCTUBRE" AS "MES";
	WHEN 11 THEN SELECT "NOVIEMBRE" AS "MES";
	WHEN 12 THEN SELECT "DICIEMBRE" AS "MES";
	ELSE SELECT "No es un mes valido" AS "MES";
	END CASE;
END $$

DELIMITER ;