CREATE DATABASE Biblioteca;

USE Biblioteca;

CREATE TABLE USUARIO (
	dni 	VARCHAR(10),
	edad 	INTEGER 	NOT NULL,
	cuota 	FLOAT 		NOT NULL,
	PRIMARY KEY(dni)
);

CREATE TABLE LIBRO (
	isbn VARCHAR(20),
	titulo VARCHAR(50) NOT NULL,
	autor VARCHAR(50) NOT NULL,
	editorial VARCHAR(50) NOT NULL,
	PRIMARY KEY(isbn)
);

CREATE TABLE PRESTAMO (
	isbn VARCHAR(20),
	dni_usuario VARCHAR(10) NOT NULL,
	fecha DATE,
	periodo INTEGER NOT NULL,
	PRIMARY KEY(isbn,fecha),
	FOREIGN KEY(isbn) REFERENCES LIBRO(isbn)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(dni_usuario) REFERENCES USUARIO(dni)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);